"""
Vyapar Setu — Feature Store (SQLite / PostgreSQL CRUD)
=======================================================
Provides CRUD operations for the weekly_features table.
This is the single source of truth for ML training data:
  - data_pipeline.py writes CSVs to data/raw/
  - feature_store.py loads those CSVs into the DB
  - forecaster.py reads from DB (or falls back to CSV)

All writes are idempotent (upsert by week_date + route).
"""
from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Optional

import pandas as pd
from loguru import logger
from sqlalchemy import text
from sqlalchemy.orm import Session

from db.database import engine, get_db

# Path to raw CSVs generated by data_pipeline
DATA_RAW = Path(__file__).parent.parent / "data" / "raw"
DATA_PROCESSED = Path(__file__).parent.parent / "data" / "processed"


def load_csv_to_db(session: Session, csv_path: Optional[Path] = None) -> int:
    """
    Ingest weekly feature CSV into the weekly_features table.
    Returns number of rows upserted.
    """
    path = csv_path or (DATA_RAW / "freight_rates.csv")
    if not path.exists():
        logger.warning(f"Feature CSV not found at {path}. Run data_pipeline.py first.")
        return 0

    df = pd.read_csv(path, parse_dates=["week_date"])
    df["created_at"] = datetime.utcnow().isoformat()

    rows = df.to_dict(orient="records")
    upserted = 0

    for row in rows:
        try:
            # Build upsert (SQLite uses INSERT OR REPLACE; PostgreSQL needs ON CONFLICT)
            cols = [k for k in row.keys() if not isinstance(row[k], float) or not pd.isna(row[k])]
            placeholders = ", ".join(f":{c}" for c in cols)
            col_names = ", ".join(cols)

            session.execute(
                text(
                    f"INSERT OR REPLACE INTO weekly_features ({col_names}) VALUES ({placeholders})"
                ),
                {c: row[c] for c in cols},
            )
            upserted += 1
        except Exception as e:
            logger.debug(f"Row upsert skipped: {e}")

    session.commit()
    logger.info(f"Feature store: upserted {upserted} rows from {path}")
    return upserted


def get_feature_df(
    session: Session,
    start_date: Optional[str] = None,
    end_date: Optional[str] = None,
    route: str = "Australia→Paradip (Panamax)",
) -> pd.DataFrame:
    """
    Read feature rows from DB into a DataFrame.
    Falls back to CSV if DB is empty.
    """
    query = "SELECT * FROM weekly_features WHERE 1=1"
    params: dict = {}

    if start_date:
        query += " AND week_date >= :start_date"
        params["start_date"] = start_date
    if end_date:
        query += " AND week_date <= :end_date"
        params["end_date"] = end_date

    query += " ORDER BY week_date ASC"

    try:
        df = pd.read_sql(text(query), session.bind, params=params)
        if not df.empty:
            return df
    except Exception as e:
        logger.warning(f"DB read failed: {e} — falling back to CSV")

    # CSV fallback
    csv_path = DATA_RAW / "freight_rates.csv"
    if csv_path.exists():
        df = pd.read_csv(csv_path, parse_dates=["week_date"])
        if start_date:
            df = df[df["week_date"] >= start_date]
        if end_date:
            df = df[df["week_date"] <= end_date]
        return df

    return pd.DataFrame()


def get_latest_features(session: Session) -> Optional[dict]:
    """Return the most recent row of features as a dict."""
    try:
        result = session.execute(
            text("SELECT * FROM weekly_features ORDER BY week_date DESC LIMIT 1")
        ).fetchone()
        if result:
            return dict(result._mapping)
    except Exception as e:
        logger.warning(f"get_latest_features failed: {e}")
    return None


def insert_congestion_event(
    session: Session,
    port: str,
    berth_wait_days: float,
    event_date: str,
    source: str = "field_agent",
) -> bool:
    """Log a field-agent reported congestion event to the audit table."""
    try:
        session.execute(
            text("""
                INSERT INTO decision_log
                    (timestamp, route, recommendation, approved_by, action, notes)
                VALUES
                    (:ts, :route, :rec, :approved_by, :action, :notes)
            """),
            {
                "ts": event_date,
                "route": f"Port congestion: {port}",
                "rec": f"berth_wait_days={berth_wait_days:.1f}",
                "approved_by": source,
                "action": "congestion_event_logged",
                "notes": f"Field agent voice note — {berth_wait_days:.1f}d berth wait reported at {port}",
            },
        )
        session.commit()
        return True
    except Exception as e:
        logger.error(f"insert_congestion_event failed: {e}")
        return False


def get_feature_summary(session: Session) -> dict:
    """Return summary statistics about the feature store."""
    try:
        result = session.execute(
            text("""
                SELECT
                    COUNT(*) as row_count,
                    MIN(week_date) as start_date,
                    MAX(week_date) as end_date,
                    AVG(freight_rate_usd_t) as avg_rate,
                    MIN(freight_rate_usd_t) as min_rate,
                    MAX(freight_rate_usd_t) as max_rate
                FROM weekly_features
            """)
        ).fetchone()
        if result:
            return dict(result._mapping)
    except Exception as e:
        logger.warning(f"Feature summary query failed: {e}")
    return {"error": "Feature store empty or unavailable"}
