"""
Vyapar Setu — Tender Specification Document Generator
======================================================
Generates a structured Microsoft Word (.docx) document containing
the complete chartering tender specification, sourced from the MILP
optimizer recommendation and SHAP driver analysis.

Uses python-docx for document assembly.
Streams the document as bytes for API download.
Also supports vernacular variant (English + regional language zip).
"""
from __future__ import annotations

import io
import zipfile
from datetime import date, datetime
from typing import Optional

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt, RGBColor
from loguru import logger


INR_USD = 83.5

_LANGUAGES = {
    "Odia":    "od",
    "Telugu":  "te",
    "Bengali": "bn",
    "Hindi":   "hi",
}

# ── Port → preferred regional language ───────────────────────────────────────
PORT_LANGUAGE: dict[str, str] = {
    "Paradip":        "Odia",
    "Dhamra":         "Odia",
    "Haldia":         "Bengali",
    "Vishakhapatnam": "Telugu",
    "Gangavaram":     "Telugu",
    "Krishnapatnam":  "Telugu",
    "Tuticorin":      "Tamil",   # Sarvam supports Tamil
}

PROCUREMENT_COUNTER = 1000   # In production, read from DB


def _heading_style(para, text: str, level: int = 1) -> None:
    para.text = text
    para.style = f"Heading {level}"


def _add_table_row(table, cells: list[str], bold_first: bool = False) -> None:
    row = table.add_row()
    for i, cell_text in enumerate(cells):
        cell = row.cells[i]
        cell.text = cell_text
        if bold_first and i == 0:
            cell.paragraphs[0].runs[0].bold = True


def generate_tender_docx(
    recommendation: dict,
    shap_drivers: list[dict],
    request_payload: dict,
    ref_number: Optional[str] = None,
    generated_by: str = "Vyapar Setu AI System",
) -> bytes:
    """
    Assemble a full tender specification document.

    Args:
        recommendation: Output dict from milp_optimizer.optimize()['recommendation']
        shap_drivers:   Output list from milp_optimizer.optimize()['shap_drivers']
        request_payload: Original optimization request (for context)
        ref_number:     Optional procurement reference number
        generated_by:   Generating entity for audit trail

    Returns:
        bytes of the .docx file
    """
    doc = Document()

    # ── Document properties ───────────────────────────────────────────────────
    ref = ref_number or f"VS/TENDER/{date.today().strftime('%Y%m%d')}/{PROCUREMENT_COUNTER:04d}"
    generated_at = datetime.now().strftime("%d %B %Y, %H:%M IST")
    dest_port = request_payload.get("destination_port", "N/A")
    cargo_t = request_payload.get("cargo_tonnes", 0)

    # ── Title ─────────────────────────────────────────────────────────────────
    title = doc.add_heading("VYAPAR SETU — CHARTERING TENDER SPECIFICATION", 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph(f"Reference No: {ref}", style="Normal").bold = True
    doc.add_paragraph(f"Generated: {generated_at}  |  Generated by: {generated_by}")
    doc.add_paragraph(f"Classification: INTERNAL — RESTRICTED")
    doc.add_horizontal_line = doc.add_paragraph("─" * 80)

    # ── Section 1: Procurement Summary ───────────────────────────────────────
    doc.add_heading("1. Procurement Summary", 1)
    summary_table = doc.add_table(rows=1, cols=2)
    summary_table.style = "Table Grid"
    summary_table.rows[0].cells[0].text = "Parameter"
    summary_table.rows[0].cells[1].text = "Value"
    summary_table.rows[0].cells[0].paragraphs[0].runs[0].bold = True
    summary_table.rows[0].cells[1].paragraphs[0].runs[0].bold = True

    summary_data = [
        ("Destination Port", dest_port),
        ("Commodity", request_payload.get("commodity", "Coal")),
        ("Required Quantity", f"{cargo_t:,} MT"),
        ("Delivery Window", f"{request_payload.get('latest_arrival_date_days', 60)} days from today"),
        ("Budget Cap (USD)", f"${request_payload.get('budget_cap_usd', 'Not set')}"),
    ]
    for k, v in summary_data:
        _add_table_row(summary_table, [k, v], bold_first=True)

    # ── Section 2: AI Recommendation ─────────────────────────────────────────
    doc.add_heading("2. AI-Recommended Charter Specification", 1)
    rec_table = doc.add_table(rows=1, cols=2)
    rec_table.style = "Table Grid"
    rec_table.rows[0].cells[0].text = "Parameter"
    rec_table.rows[0].cells[1].text = "Recommended Value"
    rec_table.rows[0].cells[0].paragraphs[0].runs[0].bold = True
    rec_table.rows[0].cells[1].paragraphs[0].runs[0].bold = True

    rec_data = [
        ("Vessel Class",        recommendation.get("vessel_class", "N/A")),
        ("Charter Timing",      recommendation.get("timing", "N/A").replace("_", " ").title()),
        ("Origin Port",         recommendation.get("origin", "N/A")),
        ("Lot Size",            f"{recommendation.get('lot_size_tonnes', 0):,} MT"),
        ("Number of Voyages",   str(recommendation.get("n_voyages", 1))),
        ("Voyage Duration",     f"{recommendation.get('voyage_days', 0)} days"),
        ("Est. Freight Cost",   f"${recommendation.get('freight_cost_usd', 0):,.0f}  (₹{recommendation.get('freight_cost_usd', 0)*INR_USD:,.0f})"),
        ("Est. Demurrage",      f"${recommendation.get('demurrage_cost_usd', 0):,.0f}"),
        ("Quality Penalty",     f"${recommendation.get('quality_penalty_usd', 0):,.0f}"),
        ("Total Cost (USD)",    f"${recommendation.get('total_cost_usd', 0):,.0f}"),
        ("Total Cost (INR)",    f"₹{recommendation.get('total_cost_inr', 0):,.0f}"),
        ("Cost per Tonne",      f"${recommendation.get('cost_per_tonne_usd', 0):.2f} / ₹{recommendation.get('cost_per_tonne_inr', 0):.2f}"),
    ]
    for k, v in rec_data:
        _add_table_row(rec_table, [k, v], bold_first=True)

    doc.add_paragraph(f"\nRationale: {recommendation.get('rationale', 'N/A')}")

    # ── Section 3: Cost Driver Analysis (SHAP) ───────────────────────────────
    doc.add_heading("3. Cost Driver Analysis", 1)
    doc.add_paragraph(
        "The following table shows the contribution of each factor to the total chartering cost, "
        "as computed by the Vyapar Setu AI attribution engine."
    )
    shap_table = doc.add_table(rows=1, cols=4)
    shap_table.style = "Table Grid"
    headers = ["Driver", "Cost Contribution (USD)", "Share (%)", "Direction"]
    for i, h in enumerate(headers):
        shap_table.rows[0].cells[i].text = h
        shap_table.rows[0].cells[i].paragraphs[0].runs[0].bold = True

    for driver in shap_drivers:
        _add_table_row(shap_table, [
            driver.get("driver", ""),
            f"${driver.get('contribution_usd', 0):,.0f}",
            f"{driver.get('contribution_pct', 0):.1f}%",
            driver.get("direction", "").capitalize(),
        ])

    # ── Section 4: Port Constraints ───────────────────────────────────────────
    doc.add_heading("4. Port Constraints & Draft Limits", 1)
    port_constraints = {
        "Paradip":        {"max_dwt": "180,000 MT", "max_draft": "18.5 m", "demurrage_rate": "USD 20,000/day"},
        "Vishakhapatnam": {"max_dwt": "160,000 MT", "max_draft": "16.5 m", "demurrage_rate": "USD 18,000/day"},
        "Haldia":         {"max_dwt": "75,000 MT",  "max_draft": "8.5 m",  "demurrage_rate": "USD 14,000/day"},
        "Krishnapatnam":  {"max_dwt": "150,000 MT", "max_draft": "15.5 m", "demurrage_rate": "USD 17,000/day"},
        "Tuticorin":      {"max_dwt": "60,000 MT",  "max_draft": "12.0 m", "demurrage_rate": "USD 12,000/day"},
        "Dhamra":         {"max_dwt": "160,000 MT", "max_draft": "16.0 m", "demurrage_rate": "USD 16,000/day"},
        "Gangavaram":     {"max_dwt": "180,000 MT", "max_draft": "18.0 m", "demurrage_rate": "USD 20,000/day"},
    }
    port_table = doc.add_table(rows=1, cols=4)
    port_table.style = "Table Grid"
    for i, h in enumerate(["Port", "Max DWT", "Max Draft", "Demurrage Rate"]):
        port_table.rows[0].cells[i].text = h
        port_table.rows[0].cells[i].paragraphs[0].runs[0].bold = True

    for port, specs in port_constraints.items():
        marker = " ← destination" if port == dest_port else ""
        _add_table_row(port_table, [
            port + marker,
            specs["max_dwt"],
            specs["max_draft"],
            specs["demurrage_rate"],
        ])

    # ── Section 5: Supplier Shortlist ────────────────────────────────────────
    doc.add_heading("5. Recommended Supplier Shortlist", 1)
    origin = recommendation.get("origin", "Australia")
    suppliers = {
        "Australia":  ["BHP Billiton (Hay Point)", "Glencore (DBCT)", "Whitehaven Coal (Newcastle)"],
        "Indonesia":  ["Adaro Energy (Kalimantan)", "Bayan Resources", "Bukit Asam"],
        "USA":        ["Arch Resources (Hampton Roads)", "CONSOL Energy (Baltimore)", "Alpha Natural Resources"],
        "Mozambique": ["Vale (Nacala)", "Kenmare Resources"],
    }.get(origin, ["N/A"])

    for s in suppliers:
        doc.add_paragraph(f"• {s}", style="List Bullet")

    doc.add_paragraph(
        "\nNote: Final supplier selection subject to quality verification, "
        "MMTC/STC approval, and GeM portal compliance."
    )

    # ── Section 6: Approval / Audit Block ────────────────────────────────────
    doc.add_heading("6. Decision Audit Block", 1)
    doc.add_paragraph(
        "This tender specification has been generated by Vyapar Setu AI and requires "
        "authorized approval before issuance. Authorized signatories must select one action:"
    )

    audit_table = doc.add_table(rows=4, cols=3)
    audit_table.style = "Table Grid"
    audit_headers = ["Action", "Authorized Signatory", "Signature & Date"]
    for i, h in enumerate(audit_headers):
        audit_table.rows[0].cells[i].text = h
        audit_table.rows[0].cells[i].paragraphs[0].runs[0].bold = True

    for action, label in [
        ("✅ APPROVE",    "GM (Procurement)"),
        ("✏️  MODIFY",    "Deputy GM (Logistics)"),
        ("❌ REJECT",    "Director (Finance)"),
    ]:
        row = audit_table.add_row()
        row.cells[0].text = action
        row.cells[1].text = label
        row.cells[2].text = "________________________"

    doc.add_paragraph(f"\n\nDocument Reference: {ref}")
    doc.add_paragraph(f"Generated by Vyapar Setu v1.0 — {generated_at}")
    doc.add_paragraph("Powered by Prophet + XGBoost AI Engine | IIT/NIT SIH 2026 Prototype")

    # ── Serialize to bytes ────────────────────────────────────────────────────
    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def generate_vernacular_zip(
    english_bytes: bytes,
    destination_port: str,
    translated_text: Optional[str] = None,
    language_override: Optional[str] = None,
) -> bytes:
    """
    Bundle English + vernacular documents into a .zip.
    If translated_text is None, adds a placeholder note.
    """
    lang = language_override or PORT_LANGUAGE.get(destination_port, "Hindi")

    # Build a minimal vernacular document
    doc_vern = Document()
    doc_vern.add_heading(f"व्यापार सेतु — टेंडर विवरण ({lang})", 0)
    doc_vern.add_paragraph(
        f"भाषा / Language: {lang}\n"
        "यह दस्तावेज़ Sarvam AI Mayura अनुवाद इंजन द्वारा तैयार किया गया है।\n"
        "This document was prepared using the Sarvam AI Mayura translation engine."
    )

    if translated_text:
        doc_vern.add_paragraph(translated_text)
    else:
        doc_vern.add_paragraph(
            "[अनुवाद उपलब्ध नहीं — Sarvam API key आवश्यक है।]\n"
            "[Translation unavailable — configure SARVAM_API_KEY in .env]"
        )

    vern_buf = io.BytesIO()
    doc_vern.save(vern_buf)
    vern_bytes = vern_buf.getvalue()

    # Zip both
    zip_buf = io.BytesIO()
    with zipfile.ZipFile(zip_buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("tender_specification_english.docx", english_bytes)
        zf.writestr(f"tender_specification_{lang.lower()}.docx", vern_bytes)

    return zip_buf.getvalue()
